config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  #users_controller
  devise_for :users
  resources :user
  resources :authentications
  get '/auth/:provider/callback' => 'authentications#create'

  #jobs_controller -> should rename this to indeed
  get '/jobs/search' => 'jobs#search', as: :job_search
  get '/jobs/:jobkey' => 'jobs#show', as: :job

  #job_details_controller
  post '/users/:user_id/job_details' => 'job_details#create', as: :user_job_details
  patch '/users/:user_id/job_details/:job_detail_id' => 'job_details#update', as: :user_job_detail
  get '/users/:user_id/jobs' => 'job_details#index', as: :user_job_details_index
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to :user
end

app/models/job_detail.rb
class JobDetail < ActiveRecord::Base
  # validates_uniqueness_of :jobkey, if: :jobkey_is_unique_to_user
  belongs_to :user
  
  private

  def jobkey_is_unique_to_user
    self.user.job_details.pluck(:jobkey).include?(self.jobkey)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :authentications
  has_many :job_details
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController

  def index
    @authentications = current_user.authentications if current_user
  end

  def create
    auth = request.env["omniauth.auth"]

    if current_user.authentications.pluck(:provider).include?(auth["provider"]) && current_user.authentications.pluck(:uid).include?(auth["uid"])  
      current_user.authentications.find_by_provider_and_uid(auth["provider"], auth["uid"])
    else
      current_user.authentications.create(provider: auth["provider"], uid: auth["uid"])
    end
    flash[:notice] = "Authentication successful."
    redirect_to authentications_url
  end

  def destroy
    @authentication = current_user.authentications.find(params[:id])
    @authentication.destroy
    flash[:notice] = "Successfully destroyed authentication."
    redirect_to authentications_url
  end
end

app/controllers/job_details_controller.rb
class JobDetailsController < ApplicationController
  def index
    @jobs = current_user.job_details

    respond_to do |format|
      format.js { render layout: false }
    end
  end
  
  def create
    @job_detail = current_user.job_details.new(jobkey: params[:jobkey], user_id: params[:user_id], company: params[:company], title: params[:title])

    respond_to do |format|
      if @job_detail.save
        format.js { render layout: false, action: "create_success" }
      else
        format.js { render layout: false, action: "create_failure" }
      end
    end
  end

  def update
    job_detail = current_user.job_details.find(params[:job_detail_id])

    respond_to do |format|
      if job_detail.update(strong_params)
        format.js { render layout: false, action: "update_success" }
      else
        format.js { render layout: false, action: "update_failure" }
      end
    end
  end

  private

  def strong_params
    params.require(:job_detail).permit(:jobkey, :user_id, :cover_letter, :note, :company, :title)
  end


end

app/controllers/jobs_controller.rb
require 'indeed-ruby'

class JobsController < ApplicationController
  before_filter :initialize_indeed_client, only: [:search, :show]

  def search

    terms = {
      q: params[:query],
      l: params[:location],
      userip: request.remote_ip,
      useragent: request.env['HTTP_USER_AGENT'],
      start: params[:start]
    }

    @pagination_variables = {
      query: params[:query],
      location: params[:location],
      start: params[:start]
    }

    #make an api call to indeed with the search query
    @jobs = @client.search(terms)["results"]

    respond_to do |format|
      format.js { render layout: false }
    end

  end

  def show

    criteria = {
      jobkeys: [ params[:jobkey] ]
    }

    searched_job = @client.jobs(criteria)

    @job = searched_job["results"][0]

    @url = replace_protocal_with_blank(@job["url"])
    @job_detail = current_user.job_details.find_by(jobkey: params[:jobkey])

    respond_to do |format|
      format.js { render layout: false }
    end

  end

  private

    def initialize_indeed_client
      @client = Indeed::Client.new('6354264415606633')
    end

    def replace_protocal_with_blank(url)
      if url.include?('https:')
        url = url.gsub("https:", "")
      else
        url = url.gsub("http:", "")
      end
      url
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @jobs = current_user.job_details
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/job_details_helper.rb
module JobDetailsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/authentications/index.haml
- @authentications.each do |auth|
  = auth.user_id
  = auth.provider
  = auth.uid
  %br

- if @authentications
  - unless @authentications.empty?
    %p
      %strong You can sign in to this account using:
    .authentications
      - for authentication in @authentications
        .authentication
          = image_tag "#{authentication.provider}_32.png", size: "32x32"
          .provider= authentication.provider.titleize
          .uid= authentication.uid
          = link_to "X", authentication, :confirm => "Are you sure you want to remove this authentication option?", method: :delete, class: "remove"
      .clear
  %p
    %strong Add another service to sign in with:
- else
  %p
    %strong Sign in through one of these services:

%a.auth_provider{ href: "/auth/linkedin" }
  = image_tag "linkedin_64.png", size: "64x64", alt: "LinkedIn"
  LinkedIn
%a.auth_provider{ href: "/auth/facebook" }
  = image_tag "facebook_64.png", size: "64x64", alt: "Facebook" 
  Facebook
%a.auth_provider{ href: "/auth/google_apps" }
  = image_tag "google_64.png", size: "64x64", alt: "Google" 
  Google
.clear

app/views/job_details/_cover_letter_form.haml
= form_for([current_user, @job_detail], remote: true, id: 'cover-letter') do |f|
  = f.text_area :cover_letter, class: "tinymce", id: "cover-letter-#{@job_detail.id}"
  = f.submit "Save", id: "cover-letter-save"

  

app/views/job_details/_note_form.haml
= form_for([current_user, @job_detail], remote: true, id: 'note') do |f|
  = f.text_area :note, class: "tinymce", id: "note-#{@job_detail.id}"
  = f.submit "Save"

  

app/views/job_details/_user_jobs.haml
- @jobs.each do |job|
  .job-card
    %b= link_to job.company, job_path(job.jobkey), remote: true
    %br
    = job.title

app/views/job_details/create_failure.js.erb
alert('fail yo');

app/views/job_details/create_success.js.erb
$('#cover-letter-wrapper').append("<%= j render 'cover_letter_form' %>")
$('#note-wrapper').append("<%= j render 'note_form' %>")

$(document).ready(function() {
  $('a#interested').hide();
  tinyMCE.editors=[]
  tinyMCE.init({ 
    selector: '.tinymce',
    height: 300
  });

});

app/views/job_details/index.js.erb
$('#results').html('')
$('#results').append("<%= j render(:partial => 'job_details/user_jobs', :locals => { :jobs => @jobs }) %>");

app/views/job_details/update_failure.js.erb
alert('failed to update')

app/views/job_details/update_success.js.erb
alert('updated')

app/views/jobs/_results.haml
- @jobs.each do |job|
  .job-card
    %b= link_to job["jobtitle"], job_path(job["jobkey"]), remote: true
    %br
    = job["company"]

app/views/jobs/_show.haml
%section
  .tabs.tabs-style-bar
    %nav
      %ul
        %li
          %a.icon.icon-home{:href => "#section-bar-1"}
            %span Job
        %li
          %a.icon.icon-box{:href => "#section-bar-2"}
            %span Website
        %li
          %a.icon.icon-display.cover-letter-tab{:href => "#section-bar-3"}
            %span Cover Letter
        %li
          %a.icon.icon-upload.note-tab{:href => "#section-bar-4"}
            %span Notes
        %li
          %a.icon.icon-tools{:href => "#section-bar-5"}
            %span Friends
    .content-wrap
      %section#section-bar-1
        %p.detail Job Title: #{@job["jobtitle"]}
        %p.detail Company: #{@job["company"]}
        %p.detail Location: #{@job["formattedLocation"]}
        %p.detail Country: #{@job["country"]}
        %p.detail Snippet: #{@job["snippet"]}
        %p.detail Url: #{ link_to "Job Link", @job["url"], target: "_blank" }
        %p.detail Posted: #{@job["formattedRelativeTime"]}
      %section#section-bar-2
        #iframe-container
          %iframe{ :width => "100%", :height => "100%" }

      %section#section-bar-3
        #cover-letter-wrapper
          - if !@job_detail
            = link_to "Interested In Job", user_job_details_path(current_user, JobDetail.new, jobkey: @job["jobkey"], company: @job["company"], title: @job["jobtitle"]), method: :post, remote: true, id: 'interested'
          - else
            = render "job_details/cover_letter_form"

            :javascript
              tinyMCE.editors=[]
              tinyMCE.init({ 
                selector: '.tinymce',
                height: 300
              });
          
      %section#section-bar-4
        #note-wrapper
          - if !@job_detail
            = link_to "Interested In Job", user_job_details_path(current_user, JobDetail.new, jobkey: @job["jobkey"], company: @job["company"], title: @job["jobtitle"]), method: :post, remote: true, id: 'interested'
          - else
            = render "job_details/note_form"

      %section#section-bar-5
        %p 5

app/views/jobs/create.js.erb
alert('saved')

app/views/jobs/search.js.erb
$('#results').html('')
$('#results').append("<%= j render(:partial => 'jobs/results', :locals => { :jobs => @jobs }) %>");
$('#hidden_query').val("<%= j @pagination_variables[:query] %>")
$('#hidden_location').val("<%= j @pagination_variables[:location] %>")
$('#hidden_start').val("<%= @pagination_variables[:start] %>")
$('#next, #prev').show()

app/views/jobs/show.js.erb
$('#show').html('');
$('#show').append("<%= j render(:partial => 'jobs/show', :locals => { :job => @job, :url => @url, :job_detail => @job_detail }) %>");



// $(document).ready(function() {
//   $('.cover-letter-tab, .note-tab').click(function() {
//     console.log($(this))
//     if ( $(this).attr('class') == 'note-tab' ) {
//       selector = '#note'
//     } else {
//       selector = '#cover-letter'
//     }

//     tinyMCE.editors=[]
//     tinyMCE.init({ 
//       selector: selector,
//       height: 300
//     });
//   })
// });


(function() {
    [].slice.call( document.querySelectorAll( '.tabs' ) ).forEach( function( el ) {
        new CBPFWTabs( el );
    });
})();

var iframe = document.getElementsByTagName('iframe')[0];
var url = "<%= j @url %>";

var getData = function (data) {
    if (data && data.query && data.query.results && data.query.results.resources && data.query.results.resources.content && data.query.results.resources.status == 200) loadHTML(data.query.results.resources.content);
    else if (data && data.error && data.error.description) loadHTML(data.error.description);
    else loadHTML("Cannot load website please go directly " + "<a href='" + url + "' target='_blank'>here</a>")
};

var loadURL = function (src) {
    url = 'https:' + src;
    var script = document.createElement('script');
    script.src = 'http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20data.headers%20where%20url%3D%22' + encodeURIComponent(url) + '%22&format=json&diagnostics=true&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys&callback=getData';
    console.log(src)
    document.body.appendChild(script);
    console.log(script);
};

var loadHTML = function (html) {
    iframe.src = 'about:blank';
    iframe.contentWindow.document.open();
    iframe.contentWindow.document.write(html.replace(/<head>/i, '<head><base href="' + url + '"><scr' + 'ipt>document.addEventListener("click", function(e) { if(e.target && e.target.nodeName == "A") { e.preventDefault(); parent.loadURL(e.target.href); } });</scr' + 'ipt>'));
    iframe.contentWindow.document.close();
} 

loadURL(url);

app/views/layouts/application.haml
!!!
%html
  %head
    %title Joborganizer
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = tinymce_assets
    = csrf_meta_tags
  %body
    #container
      .row
        .col-xs-12#nav
          - if user_signed_in?
            #user_links
              = link_to "My Jobs", user_job_details_index_path(current_user), remote: true
          #user_nav
            - if user_signed_in?
              Logged in as
              = succeed "." do
                %strong= current_user.email
              = link_to 'Edit profile', edit_user_registration_path
              |
              \#{link_to "Logout", destroy_user_session_path, method: :delete}
            - else
              = link_to "Sign up", new_user_registration_path
              |
              \#{link_to "Login", new_user_session_path}
          - flash.each do |name, msg|
            = content_tag :div, msg, id: "flash_#{name}"

      = yield
          

app/views/pages/home.haml
.row#main-row
  .col-xs-4
    %input#hidden_query{ type: 'hidden', name: 'query' }
    %input#hidden_location{ type: 'hidden', name: 'location' }
    %input#hidden_start{ type: 'hidden', name: 'start' }
    = form_tag(job_search_path, remote: true, method: 'get') do
      = text_field_tag(:query, nil, placeholder: 'Search Term')
      = text_field_tag(:location, nil, placeholder: 'Location')
      = hidden_field_tag('start', 0)
      = submit_tag('search')

    #pagination_buttons
      %a#prev.pagination{ href: "#" } Prev
      %a#next.pagination{ href: "#" } Next

    #results
      = render 'job_details/user_jobs'
      
  .col-xs-8#show-column
    #show